refactor: 4 spaces to 2 spaces

diff --git a/bin/announcement b/bin/announcement
--- a/bin/announcement
+++ b/bin/announcement
@@ -8,43 +8,43 @@ profiles=(
 )
 
 while getopts 'm:d' option; do
-    case "$option" in
-        m) msg="${OPTARG}"
-            ;;
-        d) DELETE=true
-            ;;
-        :) printf "missing argument for -%s\n" "$OPTARG" >&2
-            echo "" >&2
-            usage >&2
-            exit 1
-            ;;
-        \?) printf "ilegal option: -%s\n" "$OPTARG" >&2
-            echo "" >&2
-            usage >&2
-            exit 1
-            ;;
-    esac
+  case "$option" in
+    m) msg="${OPTARG}"
+      ;;
+    d) DELETE=true
+      ;;
+    :) printf "missing argument for -%s\n" "$OPTARG" >&2
+      echo "" >&2
+      usage >&2
+      exit 1
+      ;;
+    \?) printf "ilegal option: -%s\n" "$OPTARG" >&2
+      echo "" >&2
+      usage >&2
+      exit 1
+      ;;
+  esac
 done
 shift $((OPTIND -1))
 [ "${1:-}" = "--" ] && shift
 
 if [ "$EUID" -ne 0 ];then
-    echo "Please run this script as root"
-    exit 1
+  echo "Please run this script as root"
+  exit 1
 fi
 
 case "$OSTYPE" in
-    solaris*) platform="SOLARIS" ;;
-    darwin*)  platform="OSX" ;;
-    linux*)   platform="LINUX" ;;
-    bsd*)     platform="BSD" ;;
-    msys*)    platform="WINDOWS" ;;
-    *)        platform="unknown: $OSTYPE" ;;
+  solaris*) platform="SOLARIS" ;;
+  darwin*)  platform="OSX" ;;
+  linux*)   platform="LINUX" ;;
+  bsd*)     platform="BSD" ;;
+  msys*)    platform="WINDOWS" ;;
+  *)        platform="unknown: $OSTYPE" ;;
 esac
 
 if [[ $platform != LINUX ]]; then
-    echo "This script dose not support $platform." >&2
-    exit 1
+  echo "This script dose not support $platform." >&2
+  exit 1
 fi
 
 lines=$(echo -e "${msg}" | wc -l)
@@ -52,41 +52,41 @@ logged_users_file=/tmp/announcement_users
 
 
 for profile in ${profiles[@]}; do
-    if [ -f ${profile} ]; then
-        if [ ${DELETE} == true ]; then
-            rm -rf ${logged_users_file} || true
-            head -1 ${profile} | grep -q '^#'
-            if [ $? != 0 ]; then
-                sed -i -e '/^#/,$!d' ${profile}
-            else
-                :
-            fi
-        else
-            head -1 ${profile} | grep -q '^#'
-            if [ $? == 0 ]; then
-                if command -v whiptail > /dev/null; then
-                    rm -rf ${logged_users_file}
-                    [[ ! -f ${logged_users_file} ]] && touch ${logged_users_file}
-                    chmod 777 ${logged_users_file}
-                    # rm -rf ${logged_users_file}
-                    # [[ ! -f ${logged_users_file} ]] && touch logged_users_file
-                    # sed -i -e "1i whiptail --title 'Announcement' --msgbox '${msg}' "'${height} ${width}' ${profile}
-                    sed -i -e '1i fi' ${profile}
-                    sed -i -e '1i [[ " ${logged_users[@]} " =~ " ${me} " ]] && (whiptail --title  "Announcement" --msgbox "'"${msg}"'" ${height} ${width}; echo ${logged_users[@]/$me} > ${logged_users_file} ) || true' ${profile}
-                    sed -i -e '1i me=$(whoami)' ${profile}
-                    sed -i -e '1i logged_users=( $(<${logged_users_file}) )' ${profile}
-                    sed -i -e '1i if [[ -f ${logged_users_file} ]]; then' ${profile}
-                    sed -i -e '1i [ ${COLUMNS} -lt 100 ] && width=$(( ${COLUMNS} - 10 )) || width=100' ${profile}
-                    sed -i -e '1i [ ${LINES} -lt 10 ] && height=$(( ${LINES} - 5 )) || height='"$(( 10 + ${lines} ))" ${profile}
-                    sed -i -e '1i eval `resize`' ${profile}
-                    sed -i -e '1i [[ $- == *i* && -z $TMUX ]] && echo $(whoami) >> ${logged_users_file} || true' ${profile}
-                    sed -i -e "1i logged_users_file=/tmp/announcement_users" ${profile}
-                fi
-                sed -i -e "1i echo ''" -e "1i echo ''" -e "1i echo -e '\\\033[0;93mAnnouncement ($(date +%c)):\\\033[0;0m'" -e "1i echo -e \"\\\033[0;93m${msg}\\\033[0;0m\"" ${profile}
-            else
-                echo 'announce exists' >&2
-            fi
+  if [ -f ${profile} ]; then
+    if [ ${DELETE} == true ]; then
+      rm -rf ${logged_users_file} || true
+      head -1 ${profile} | grep -q '^#'
+      if [ $? != 0 ]; then
+        sed -i -e '/^#/,$!d' ${profile}
+      else
+        :
+      fi
+    else
+      head -1 ${profile} | grep -q '^#'
+      if [ $? == 0 ]; then
+        if command -v whiptail > /dev/null; then
+          rm -rf ${logged_users_file}
+          [[ ! -f ${logged_users_file} ]] && touch ${logged_users_file}
+          chmod 777 ${logged_users_file}
+          # rm -rf ${logged_users_file}
+          # [[ ! -f ${logged_users_file} ]] && touch logged_users_file
+          # sed -i -e "1i whiptail --title 'Announcement' --msgbox '${msg}' "'${height} ${width}' ${profile}
+          sed -i -e '1i fi' ${profile}
+          sed -i -e '1i [[ " ${logged_users[@]} " =~ " ${me} " ]] && (whiptail --title  "Announcement" --msgbox "'"${msg}"'" ${height} ${width}; echo ${logged_users[@]/$me} > ${logged_users_file} ) || true' ${profile}
+          sed -i -e '1i me=$(whoami)' ${profile}
+          sed -i -e '1i logged_users=( $(<${logged_users_file}) )' ${profile}
+          sed -i -e '1i if [[ -f ${logged_users_file} ]]; then' ${profile}
+          sed -i -e '1i [ ${COLUMNS} -lt 100 ] && width=$(( ${COLUMNS} - 10 )) || width=100' ${profile}
+          sed -i -e '1i [ ${LINES} -lt 10 ] && height=$(( ${LINES} - 5 )) || height='"$(( 10 + ${lines} ))" ${profile}
+          sed -i -e '1i eval `resize`' ${profile}
+          sed -i -e '1i [[ $- == *i* && -z $TMUX ]] && echo $(whoami) >> ${logged_users_file} || true' ${profile}
+          sed -i -e "1i logged_users_file=/tmp/announcement_users" ${profile}
         fi
+        sed -i -e "1i echo ''" -e "1i echo ''" -e "1i echo -e '\\\033[0;93mAnnouncement ($(date +%c)):\\\033[0;0m'" -e "1i echo -e \"\\\033[0;93m${msg}\\\033[0;0m\"" ${profile}
+      else
+        echo 'announce exists' >&2
+      fi
     fi
+  fi
 done
 
diff --git a/bin/easy-pssh b/bin/easy-pssh
--- a/bin/easy-pssh
+++ b/bin/easy-pssh
@@ -15,16 +15,16 @@ ASKPASS=''
 
 
 case "$OSTYPE" in
-    solaris*) platform="SOLARIS" ;;
-    darwin*)  platform="OSX" ;;
-    linux*)   platform="LINUX" ;;
-    bsd*)     platform="BSD" ;;
-    msys*)    platform="WINDOWS" ;;
-    *)        platform="unknown: $OSTYPE" ;;
+  solaris*) platform="SOLARIS" ;;
+  darwin*)  platform="OSX" ;;
+  linux*)   platform="LINUX" ;;
+  bsd*)     platform="BSD" ;;
+  msys*)    platform="WINDOWS" ;;
+  *)        platform="unknown: $OSTYPE" ;;
 esac
 
 usage() {
-    LESS=-FEXR less <<HELP
+  LESS=-FEXR less <<HELP
 
 ${BRed}SYNOPSIS${Color_Off}
     ${BRed}$(basename "$0")${Color_Off} [${BRed}-iAh${Color_Off}] ${BGreen}hosts_file${Color_Off} ${BGreen}command...${Color_Off}
@@ -53,78 +53,78 @@ HELP
 }
 
 while getopts 'hiA' option; do
-    case "$option" in
-        h) usage
-            exit
-            ;;
-        A) ASKPASS='-A'
-            ;;
-        i) INLINE=true
-            ;;
-        :) printf "missing argument for -%s\n" "$OPTARG" >&2
-            echo "" >&2
-            usage >&2
-            exit 1
-            ;;
-        \?) printf "ilegal option: -%s\n" "$OPTARG" >&2
-            echo "" >&2
-            usage >&2
-            exit 1
-            ;;
-    esac
+  case "$option" in
+    h) usage
+      exit
+      ;;
+    A) ASKPASS='-A'
+      ;;
+    i) INLINE=true
+      ;;
+    :) printf "missing argument for -%s\n" "$OPTARG" >&2
+      echo "" >&2
+      usage >&2
+      exit 1
+      ;;
+    \?) printf "ilegal option: -%s\n" "$OPTARG" >&2
+      echo "" >&2
+      usage >&2
+      exit 1
+      ;;
+  esac
 done
 shift $((OPTIND -1))
 [ "${1:-}" = "--" ] && shift
 
 err() {
-  printf "${BRed}%s${Color_Off}\n" "$*" >&2
+ printf "${BRed}%s${Color_Off}\n" "$*" >&2
 }
 
 has() {
-    local verbose=0
-    if [[ $1 = '-v' ]]; then
-        verbose=1
-        shift
+  local verbose=0
+  if [[ $1 = '-v' ]]; then
+    verbose=1
+    shift
+  fi
+  for c; do c="${c%% *}"
+    if ! command -v "$c" &> /dev/null; then
+      (( verbose > 0 )) && err "$c not found"
+      return 1
     fi
-    for c; do c="${c%% *}"
-        if ! command -v "$c" &> /dev/null; then
-            (( verbose > 0 )) && err "$c not found"
-            return 1
-        fi
-    done
+  done
 }
 
 easy-pssh() { # Easy pssh command
-    local hosts_file="$1"; shift
-    local cmd="$@"
-    local n_host=$(wc -l < ${hosts_file})
+  local hosts_file="$1"; shift
+  local cmd="$@"
+  local n_host=$(wc -l < ${hosts_file})
 
-    if [ ${INLINE} == false ]; then
-        local tmpdir=$(mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir')
-    fi
+  if [ ${INLINE} == false ]; then
+    local tmpdir=$(mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir')
+  fi
 
-    sudo=$(echo $cmd | awk '{print $1}')
+  sudo=$(echo $cmd | awk '{print $1}')
 
-    if [[ $sudo == 'sudo' ]]; then
-        echo "Enter the sudo passwd for the remote user: "
-        read -s pswd
+  if [[ $sudo == 'sudo' ]]; then
+    echo "Enter the sudo passwd for the remote user: "
+    read -s pswd
 
-        if [[ ${INLINE} == true ]]; then
-            echo "$pswd" | pssh -p ${n_host} -t 0 -h ${hosts_file} ${ASKPASS} -i -I "sudo -S -- sh -c '$cmd'"
-        else
-            echo "${Yellow}[${BIYellow}logdir${Yellow}]${Color_Off} ${tmpdir}"
-            echo
-            echo "$pswd" | pssh -p ${n_host} -t 0 -h ${hosts_file} ${ASKPASS} -o ${tmpdir}/pssh_outdir -e ${tmpdir}/pssh_errdir -I "sudo -S -- sh -c '$cmd'"
-        fi
+    if [[ ${INLINE} == true ]]; then
+      echo "$pswd" | pssh -p ${n_host} -t 0 -h ${hosts_file} ${ASKPASS} -i -I "sudo -S -- sh -c '$cmd'"
     else
-        if [[ ${INLINE} == true ]]; then
-            pssh -p ${n_host} -h ${hosts_file} ${ASKPASS} -t 0 -i "$cmd"
-        else
-            echo "${Yellow}[${BIYellow}logdir${Yellow}]${Color_Off} ${tmpdir}"
-            echo
-            pssh -p ${n_host} -h ${hosts_file} -t 0 ${ASKPASS} -o ${tmpdir}/pssh_outdir -e ${tmpdir}/pssh_errdir "$cmd"
-        fi
+      echo "${Yellow}[${BIYellow}logdir${Yellow}]${Color_Off} ${tmpdir}"
+      echo
+      echo "$pswd" | pssh -p ${n_host} -t 0 -h ${hosts_file} ${ASKPASS} -o ${tmpdir}/pssh_outdir -e ${tmpdir}/pssh_errdir -I "sudo -S -- sh -c '$cmd'"
     fi
+  else
+    if [[ ${INLINE} == true ]]; then
+      pssh -p ${n_host} -h ${hosts_file} ${ASKPASS} -t 0 -i "$cmd"
+    else
+      echo "${Yellow}[${BIYellow}logdir${Yellow}]${Color_Off} ${tmpdir}"
+      echo
+      pssh -p ${n_host} -h ${hosts_file} -t 0 ${ASKPASS} -o ${tmpdir}/pssh_outdir -e ${tmpdir}/pssh_errdir "$cmd"
+    fi
+  fi
 }
 
 has -v pssh || exit 1
diff --git a/bin/easy-useradd b/bin/easy-useradd
--- a/bin/easy-useradd
+++ b/bin/easy-useradd
@@ -16,21 +16,21 @@ DEFAULT_GROUP="$(groups | awk '{print $1}')"
 
 
 case "$OSTYPE" in
-    solaris*) platform="SOLARIS" ;;
-    darwin*)  platform="OSX" ;;
-    linux*)   platform="LINUX" ;;
-    bsd*)     platform="BSD" ;;
-    msys*)    platform="WINDOWS" ;;
-    *)        platform="unknown: $OSTYPE" ;;
+  solaris*) platform="SOLARIS" ;;
+  darwin*)  platform="OSX" ;;
+  linux*)   platform="LINUX" ;;
+  bsd*)     platform="BSD" ;;
+  msys*)    platform="WINDOWS" ;;
+  *)        platform="unknown: $OSTYPE" ;;
 esac
 
 if [[ $platform != LINUX ]]; then
-    echo "This script dose not support $platform." >&2
-    exit 1
+  echo "This script dose not support $platform." >&2
+  exit 1
 fi
 
 usage() {
-    LESS=-FEXR less <<HELP
+  LESS=-FEXR less <<HELP
 
 ${BRed}SYNOPSIS${Color_Off}
     ${BRed}$(basename "$0")${Color_Off} [${BRed}-hs${Color_Off}] [${BRed}-g${Color_Off} ${BGreen}default_group${Color_Off}] [${BRed}-p${Color_Off} ${BGreen}default_passwd${Color_Off}] ${BGreen}username${Color_Off}
@@ -65,52 +65,52 @@ HELP
 }
 
 while getopts 'p:g:hs' option; do
-    case "$option" in
-        h) usage
-            exit
-            ;;
-        s) SUDOUSER=true
-            ;;
-        g) DEFAULT_GROUP=${OPTARG}
-            ;;
-        p) DEFAULT_PASSWD=${OPTARG}
-            ;;
-        :) printf "missing argument for -%s\n" "$OPTARG" >&2
-            echo "" >&2
-            usage >&2
-            exit 1
-            ;;
-        \?) printf "ilegal option: -%s\n" "$OPTARG" >&2
-            echo "" >&2
-            usage >&2
-            exit 1
-            ;;
-    esac
+  case "$option" in
+    h) usage
+      exit
+      ;;
+    s) SUDOUSER=true
+      ;;
+    g) DEFAULT_GROUP=${OPTARG}
+      ;;
+    p) DEFAULT_PASSWD=${OPTARG}
+      ;;
+    :) printf "missing argument for -%s\n" "$OPTARG" >&2
+      echo "" >&2
+      usage >&2
+      exit 1
+      ;;
+    \?) printf "ilegal option: -%s\n" "$OPTARG" >&2
+      echo "" >&2
+      usage >&2
+      exit 1
+      ;;
+  esac
 done
 shift $((OPTIND -1))
 [ "${1:-}" = "--" ] && shift
 
 if [ "$EUID" -ne 0 ];then
-    echo "Please run this script as root"
-    exit 1
+  echo "Please run this script as root"
+  exit 1
 fi
 
 if [ "${1:?you have to specify user name}" == "guest" ]; then
-    useradd guest -m -s /bin/bash
-    echo "$1:$DEFAULT_PASSWD" | chpasswd
-    chown root.${DEFAULT_GROUP} /home/guest
-    chmod 755 /home/guest
+  useradd guest -m -s /bin/bash
+  echo "$1:$DEFAULT_PASSWD" | chpasswd
+  chown root.${DEFAULT_GROUP} /home/guest
+  chmod 755 /home/guest
 else
-    # create user
-    useradd "$1" -m -g ${DEFAULT_GROUP} -s /bin/bash
-    echo "$1:$DEFAULT_PASSWD" | chpasswd
-    passwd --expire "$1"
+  # create user
+  useradd "$1" -m -g ${DEFAULT_GROUP} -s /bin/bash
+  echo "$1:$DEFAULT_PASSWD" | chpasswd
+  passwd --expire "$1"
 
-    # add user to sudo group
-    if [ "$SUDOUSER" == true ]; then
-        usermod -a -G sudo "$1"
-    fi
+  # add user to sudo group
+  if [ "$SUDOUSER" == true ]; then
+    usermod -a -G sudo "$1"
+  fi
 
-    # change the authority
-    chmod 700 /home/"$1"
+  # change the authority
+  chmod 700 /home/"$1"
 fi
diff --git a/bin/gpustat b/bin/gpustat
--- a/bin/gpustat
+++ b/bin/gpustat
@@ -5,28 +5,28 @@ trap "echo 'error: Script failed: see failed command above'" ERR
 IFS=$'\n\t'
 
 vercomp () {
-    if [[ $1 == $2 ]]; then
-        echo 0
-    fi
-    local IFS=.
-    local i ver1=($1) ver2=($2)
-    # fill empty fields in ver1 with zeros
-    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++)); do
-        ver1[i]=0
-    done
-    for ((i=0; i<${#ver1[@]}; i++)); do
-        if [[ -z ${ver2[i]+x} ]]; then
-            # fill empty fields in ver2 with zeros
-            ver2[i]=0
-        fi
-        if (( 10#${ver1[i]} > 10#${ver2[i]} )); then
-            echo 1
-        fi
-        if (( 10#${ver1[i]} < 10#${ver2[i]} )); then
-            echo 2
-        fi
-    done
+  if [[ $1 == $2 ]]; then
     echo 0
+  fi
+  local IFS=.
+  local i ver1=($1) ver2=($2)
+  # fill empty fields in ver1 with zeros
+  for ((i=${#ver1[@]}; i<${#ver2[@]}; i++)); do
+    ver1[i]=0
+  done
+  for ((i=0; i<${#ver1[@]}; i++)); do
+    if [[ -z ${ver2[i]+x} ]]; then
+      # fill empty fields in ver2 with zeros
+      ver2[i]=0
+    fi
+    if (( 10#${ver1[i]} > 10#${ver2[i]} )); then
+      echo 1
+    fi
+    if (( 10#${ver1[i]} < 10#${ver2[i]} )); then
+      echo 2
+    fi
+  done
+  echo 0
 }
 
 
@@ -104,7 +104,7 @@ On_ICyan='[0;106m'    # Cyan
 On_IWhite='[0;107m'   # White
 
 usage() {
-    LESS=-FEXR less <<HELP
+  LESS=-FEXR less <<HELP
 
 ${BRed}SYNOPSIS${Reset}
     ${BRed}$(basename "$0")${Reset} [${BRed}-u${Reset}] [${BRed}-p${Reset}] [${BRed}-w${Reset}] [${BRed}-c${Reset}] [${BRed}-h${Reset}] [${BRed}-i${Reset} ${BGreen}interval${Reset}] [${BRed}--no-header${Reset}]
@@ -142,9 +142,9 @@ HELP
 }
 
 error(){
-    echo "$(basename "$0"): invalid option -- '$1'";
-    echo "Try '$(basename "$0") -h' for more information.";
-    exit 1;
+  echo "$(basename "$0"): invalid option -- '$1'";
+  echo "Try '$(basename "$0") -h' for more information.";
+  exit 1;
 }
 
 ARGS=""
@@ -155,48 +155,48 @@ SHOW_CMD=0
 SHOW_USER=2
 INTERVAL=0
 for pass in 1 2; do
-    while [ ! -z ${1+x} ] && [ -n "$1" ]; do
-        case $1 in
-            ' --') shift; break;;
-            -*) case $1 in
-                --no-header)        SHOW_HEADER=0;;
-                -p|--show-pid)      SHOW_PID=1; [ ${SHOW_USER} == 1 ] || SHOW_USER=0;;
-                -w|--show-power)    SHOW_POWER=1; ;;
-                -c|--show-cmd)      SHOW_CMD=1; [ ${SHOW_USER} == 1 ] || SHOW_USER=0;;
-                -u|--show-user)     SHOW_USER=1;;
-                -i|--interval)      INTERVAL=${2}; shift;;
-                -h|--help)          usage; exit 0;;
-                --*)                error $1;;
-                -*)                 if [ $pass -eq 1 ]; then ARGS="$ARGS $1";
-                                    else error $1; fi;;
-                esac;;
-            *)  if [ $pass -eq 1 ]; then ARGS="$ARGS $1";
-                else error $1; fi;;
-        esac
-        shift
-    done
-    if [ $pass -eq 1 ]; then ARGS=`getopt cpwhi: $ARGS`
-        if [ $? != 0 ]; then usage; exit 2; fi; set -- $ARGS
-    fi
+  while [ ! -z ${1+x} ] && [ -n "$1" ]; do
+    case $1 in
+      ' --') shift; break;;
+      -*) case $1 in
+        --no-header)        SHOW_HEADER=0;;
+        -p|--show-pid)      SHOW_PID=1; [ ${SHOW_USER} == 1 ] || SHOW_USER=0;;
+        -w|--show-power)    SHOW_POWER=1; ;;
+        -c|--show-cmd)      SHOW_CMD=1; [ ${SHOW_USER} == 1 ] || SHOW_USER=0;;
+        -u|--show-user)     SHOW_USER=1;;
+        -i|--interval)      INTERVAL=${2}; shift;;
+        -h|--help)          usage; exit 0;;
+        --*)                error $1;;
+        -*)                 if [ $pass -eq 1 ]; then ARGS="$ARGS $1";
+                  else error $1; fi;;
+        esac;;
+      *)  if [ $pass -eq 1 ]; then ARGS="$ARGS $1";
+        else error $1; fi;;
+    esac
+    shift
+  done
+  if [ $pass -eq 1 ]; then ARGS=`getopt cpwhi: $ARGS`
+    if [ $? != 0 ]; then usage; exit 2; fi; set -- $ARGS
+  fi
 done
 
 # Handle positional arguments
 if [ -n "$*" ]; then
-    error "$*"
+  error "$*"
 fi
 
 case "$OSTYPE" in
-    solaris*) platform="SOLARIS" ;;
-    darwin*)  platform="OSX" ;;
-    linux*)   platform="LINUX" ;;
-    bsd*)     platform="BSD" ;;
-    msys*)    platform="WINDOWS" ;;
-    *)        platform="unknown: $OSTYPE" ;;
+  solaris*) platform="SOLARIS" ;;
+  darwin*)  platform="OSX" ;;
+  linux*)   platform="LINUX" ;;
+  bsd*)     platform="BSD" ;;
+  msys*)    platform="WINDOWS" ;;
+  *)        platform="unknown: $OSTYPE" ;;
 esac
 
 if [[ $platform != LINUX ]]; then
-    echo "This script dose not support $platform." >&2
-    exit 1
+  echo "This script dose not support $platform." >&2
+  exit 1
 fi
 
 command -v nvidia-smi >/dev/null || ( echo "nvidia-smi command not found" >&2; exit 1 )
@@ -214,225 +214,225 @@ declare -A gpus
 names=($(nvidia-smi --query-gpu=name --format=csv,noheader,nounits))
 max_length=0
 for name in ${names[@]}; do
-    if [ ${#name} -gt ${max_length} ]; then
-        max_length=${#name}
-    fi
+  if [ ${#name} -gt ${max_length} ]; then
+    max_length=${#name}
+  fi
 done
 max_length=$(( ${max_length} + 2 ))
 
 while true; do
 
-    gpus_order=()
+  gpus_order=()
 
-    # coproc basicfd { nvidia-smi --query-gpu=gpu_uuid,name,temperature.gpu,utilization.gpu,power.draw,power.limit,memory.used,memory.total --format=csv,noheader,nounits; }
-    # exec 3>&${basicfd[0]}
-    # coproc perfd { nvidia-smi --query-compute-apps=gpu_uuid,pid,used_memory --format=csv,noheader,nounits; }
-    # exec 4>&${perfd[0]}
-    # basic_info=$(cat <&3)
-    # per_info=$(cat <&4)
-    basic_info=$(nvidia-smi --query-gpu=gpu_uuid,name,temperature.gpu,utilization.gpu,power.draw,power.limit,memory.used,memory.total --format=csv,noheader,nounits)
-    per_info=$(nvidia-smi --query-compute-apps=gpu_uuid,pid,used_memory --format=csv,noheader,nounits)
+  # coproc basicfd { nvidia-smi --query-gpu=gpu_uuid,name,temperature.gpu,utilization.gpu,power.draw,power.limit,memory.used,memory.total --format=csv,noheader,nounits; }
+  # exec 3>&${basicfd[0]}
+  # coproc perfd { nvidia-smi --query-compute-apps=gpu_uuid,pid,used_memory --format=csv,noheader,nounits; }
+  # exec 4>&${perfd[0]}
+  # basic_info=$(cat <&3)
+  # per_info=$(cat <&4)
+  basic_info=$(nvidia-smi --query-gpu=gpu_uuid,name,temperature.gpu,utilization.gpu,power.draw,power.limit,memory.used,memory.total --format=csv,noheader,nounits)
+  per_info=$(nvidia-smi --query-compute-apps=gpu_uuid,pid,used_memory --format=csv,noheader,nounits)
 
-    ctr=0
+  ctr=0
+  while IFS= read -r line; do
+    line_=$(awk -F, 'BEGIN {OFS = ","} {print substr($0, index($0,$2))}' <(echo ${line}))
+    line_="${ctr},${line_}"
+    gpus["$(awk -F, '{print $1}' <(echo ${line}))"]="${line_}"
+    gpus_order+=("$(awk -F, '{print $1}' <(echo ${line}))")
+    ctr=$(( ${ctr} + 1 ))
+  done <<< "${basic_info}"
+
+  if [ ! -z "${per_info}" ]; then
     while IFS= read -r line; do
-        line_=$(awk -F, 'BEGIN {OFS = ","} {print substr($0, index($0,$2))}' <(echo ${line}))
-        line_="${ctr},${line_}"
-        gpus["$(awk -F, '{print $1}' <(echo ${line}))"]="${line_}"
-        gpus_order+=("$(awk -F, '{print $1}' <(echo ${line}))")
-        ctr=$(( ${ctr} + 1 ))
-    done <<< "${basic_info}"
+      uuid=$(cut -d ',' -f 1 <(echo ${line}) | tr -d '[:space:]')
+      pid=$(cut -d ',' -f 2 <(echo ${line}) | tr -d '[:space:]')
+      memory=$(cut -d ',' -f 3 <(echo ${line}) | tr -d '[:space:]')
+      user=$(stat -c "%U" /proc/${pid})
+      comm=$(cat /proc/${pid}/comm)
+      gpus[${uuid}]="${gpus[${uuid}]}, ${user}, ${comm}, ${pid}, ${memory}"
+    done <<< "${per_info}"
+  fi
 
-    if [ ! -z "${per_info}" ]; then
-        while IFS= read -r line; do
-            uuid=$(cut -d ',' -f 1 <(echo ${line}) | tr -d '[:space:]')
-            pid=$(cut -d ',' -f 2 <(echo ${line}) | tr -d '[:space:]')
-            memory=$(cut -d ',' -f 3 <(echo ${line}) | tr -d '[:space:]')
-            user=$(stat -c "%U" /proc/${pid})
-            comm=$(cat /proc/${pid}/comm)
-            gpus[${uuid}]="${gpus[${uuid}]}, ${user}, ${comm}, ${pid}, ${memory}"
-        done <<< "${per_info}"
-    fi
+  if [ ${INTERVAL} -gt 0 ]; then
+    tput reset
+  fi
 
-    if [ ${INTERVAL} -gt 0 ]; then
-        tput reset
-    fi
+  if [ ${SHOW_HEADER} -eq 1 ]; then
+    printf "${BIWhite}%s${Reset}    %s ${IBlack}%s${Reset}\n" $(hostname) $(date) $(nvidia-smi -i 0 --query-gpu=driver_version --format=csv,noheader)
+  fi
 
-    if [ ${SHOW_HEADER} -eq 1 ]; then
-        printf "${BIWhite}%s${Reset}    %s ${IBlack}%s${Reset}\n" $(hostname) $(date) $(nvidia-smi -i 0 --query-gpu=driver_version --format=csv,noheader)
-    fi
+  for uuid in "${gpus_order[@]}"; do
+    awk -F ', ' -v SHOW_PID="${SHOW_PID}" -v SHOW_POWER="${SHOW_POWER}" -v SHOW_CMD="${SHOW_CMD}" -v SHOW_USER="${SHOW_USER}" '
+  function bold() {
+    printf "\033[1m";
+  }
 
-    for uuid in "${gpus_order[@]}"; do
-        awk -F ', ' -v SHOW_PID="${SHOW_PID}" -v SHOW_POWER="${SHOW_POWER}" -v SHOW_CMD="${SHOW_CMD}" -v SHOW_USER="${SHOW_USER}" '
-    function bold() {
-        printf "\033[1m";
+  function red() {
+    printf "\033[31m";
+  }
+
+  function redI() {
+    printf "\033[91m";
+  }
+
+  function yellow() {
+    printf "\033[33m";
+  }
+
+  function yellowI() {
+    printf "\033[93m";
+  }
+
+  function white() {
+    printf "\033[97m";
+  }
+
+  function green() {
+    printf "\033[32m";
+  }
+
+  function greenI() {
+    printf "\033[92m";
+  }
+
+  function cyan() {
+    printf "\033[36m"
+  }
+
+  function cyanI() {
+    printf "\033[96m"
+  }
+
+  function purple() {
+    printf "\033[35m"
+  }
+
+  function purpleI() {
+    printf "\033[95m"
+  }
+
+  function blue() {
+    printf "\033[34m"
+  }
+
+  function blueI() {
+    printf "\033[94m"
+  }
+
+  function black() {
+    printf "\033[30m"
+  }
+
+  function blackI() {
+    printf "\033[90m"
+  }
+
+  function reset() {
+    printf "\033[0;39m";
+  }
+
+  {
+    cyan()
+    printf "[%s] ", $1
+    reset()
+
+    blue()
+    printf "%-'${max_length}'s", $2
+    reset()
+
+    printf " | "
+
+    bold()
+    red()
+    printf "%dC", $3
+    reset()
+
+    printf ", "
+
+    bold()
+    green()
+    printf "%3d %", $4
+    reset()
+
+    if ( SHOW_POWER == 1 ) {
+      printf ", "
+
+      bold()
+      purple()
+      printf "%3d", $5
+      reset()
+
+      printf " / "
+
+      purple()
+      printf "%3d W", $6
+      reset()
     }
 
-    function red() {
-        printf "\033[31m";
-    }
+    printf " | "
 
-    function redI() {
-        printf "\033[91m";
-    }
+    bold()
+    yellow()
+    printf "%5d", $7
+    reset()
 
-    function yellow() {
-        printf "\033[33m";
-    }
+    printf " / "
 
-    function yellowI() {
-        printf "\033[93m";
-    }
+    yellow()
+    printf "%5d", $8
+    reset()
 
-    function white() {
-        printf "\033[97m";
-    }
+    printf " MB |"
 
-    function green() {
-        printf "\033[32m";
-    }
-
-    function greenI() {
-        printf "\033[92m";
-    }
-
-    function cyan() {
-        printf "\033[36m"
-    }
-
-    function cyanI() {
-        printf "\033[96m"
-    }
-
-    function purple() {
-        printf "\033[35m"
-    }
-
-    function purpleI() {
-        printf "\033[95m"
-    }
-
-    function blue() {
-        printf "\033[34m"
-    }
-
-    function blueI() {
-        printf "\033[94m"
-    }
-
-    function black() {
-        printf "\033[30m"
-    }
-
-    function blackI() {
-        printf "\033[90m"
-    }
-
-    function reset() {
-        printf "\033[0;39m";
-    }
-
-    {
-        cyan()
-        printf "[%s] ", $1
-        reset()
-
-        blue()
-        printf "%-'${max_length}'s", $2
-        reset()
-
-        printf " | "
-
+    for (i=9; i < NF; ) {
+      printf " "
+      if ( SHOW_USER > 0 ) {
         bold()
-        red()
-        printf "%dC", $3
+        blackI()
+        printf "%s", $i
         reset()
+      }
 
-        printf ", "
-
-        bold()
-        green()
-        printf "%3d %", $4
-        reset()
-
-        if ( SHOW_POWER == 1 ) {
-            printf ", "
-
-            bold()
-            purple()
-            printf "%3d", $5
-            reset()
-
-            printf " / "
-
-            purple()
-            printf "%3d W", $6
-            reset()
+      i = i + 1
+      if ( SHOW_CMD == 1 ) {
+        if ( SHOW_USER > 0 ) {
+          printf ":"
         }
 
-        printf " | "
-
-        bold()
-        yellow()
-        printf "%5d", $7
+        cyanI()
+        printf "%s", $i
         reset()
+      }
 
-        printf " / "
-
-        yellow()
-        printf "%5d", $8
-        reset()
-
-        printf " MB |"
-
-        for (i=9; i < NF; ) {
-            printf " "
-            if ( SHOW_USER > 0 ) {
-                bold()
-                blackI()
-                printf "%s", $i
-                reset()
-            }
-
-            i = i + 1
-            if ( SHOW_CMD == 1 ) {
-                if ( SHOW_USER > 0 ) {
-                    printf ":"
-                }
-
-                cyanI()
-                printf "%s", $i
-                reset()
-            }
-
-            i = i + 1
-            if ( SHOW_PID == 1 ) {
-                if ( SHOW_USER > 0 || SHOW_CMD == 1 ) {
-                    printf "/"
-                }
-
-                white()
-                printf "%s", $i
-                reset()
-            }
-
-            printf "("
-            i = i + 1
-
-            yellow()
-            printf "%dM", $i
-            reset()
-
-            printf ")"
-            i = i + 1
+      i = i + 1
+      if ( SHOW_PID == 1 ) {
+        if ( SHOW_USER > 0 || SHOW_CMD == 1 ) {
+          printf "/"
         }
 
-        printf "\n"
+        white()
+        printf "%s", $i
+        reset()
+      }
 
-    }' <(echo "${gpus[${uuid}]}")
-    done
-    if [ ${INTERVAL} -gt 0 ]; then
-        sleep ${INTERVAL}
-    else
-        break
-    fi
+      printf "("
+      i = i + 1
+
+      yellow()
+      printf "%dM", $i
+      reset()
+
+      printf ")"
+      i = i + 1
+    }
+
+    printf "\n"
+
+  }' <(echo "${gpus[${uuid}]}")
+  done
+  if [ ${INTERVAL} -gt 0 ]; then
+    sleep ${INTERVAL}
+  else
+    break
+  fi
 done
diff --git a/bin/list-users b/bin/list-users
--- a/bin/list-users
+++ b/bin/list-users
@@ -19,21 +19,21 @@ GROUP_LIST=()
 
 
 case "$OSTYPE" in
-    solaris*) platform="SOLARIS" ;;
-    darwin*)  platform="OSX" ;;
-    linux*)   platform="LINUX" ;;
-    bsd*)     platform="BSD" ;;
-    msys*)    platform="WINDOWS" ;;
-    *)        platform="unknown: $OSTYPE" ;;
+  solaris*) platform="SOLARIS" ;;
+  darwin*)  platform="OSX" ;;
+  linux*)   platform="LINUX" ;;
+  bsd*)     platform="BSD" ;;
+  msys*)    platform="WINDOWS" ;;
+  *)        platform="unknown: $OSTYPE" ;;
 esac
 
 if [[ $platform != LINUX ]]; then
-    echo "This script dose not support $platform." >&2
-    exit 1
+  echo "This script dose not support $platform." >&2
+  exit 1
 fi
 
 usage() {
-    LESS=-FEXR less <<HELP
+  LESS=-FEXR less <<HELP
 
 ${BRed}SYNOPSIS${Color_Off}
     ${BRed}$(basename "$0")${Color_Off} [${BRed}-hsl${Color_Off}]
@@ -60,31 +60,31 @@ HELP
 }
 
 while getopts 'g:hsl' option; do
-    case "$option" in
-        h) usage
-            exit
-            ;;
-        s) SYSTEM_USERS=true
-            ;;
-        l) LOCKED_USERS=true
-            if ! [ "$EUID" -eq 0 ]; then
-                echo 'Need privilege to list locked users' >&2
-                exit 1
-            fi
-            ;;
-        g) GROUP_LIST=(${OPTARG//,/ })
-            ;;
-        :) printf "missing argument for -%s\n" "$OPTARG" >&2
-            echo "" >&2
-            usage >&2
-            exit 1
-            ;;
-        \?) printf "ilegal option: -%s\n" "$OPTARG" >&2
-            echo "" >&2
-            usage >&2
-            exit 1
-            ;;
-    esac
+  case "$option" in
+    h) usage
+      exit
+      ;;
+    s) SYSTEM_USERS=true
+      ;;
+    l) LOCKED_USERS=true
+      if ! [ "$EUID" -eq 0 ]; then
+        echo 'Need privilege to list locked users' >&2
+        exit 1
+      fi
+      ;;
+    g) GROUP_LIST=(${OPTARG//,/ })
+      ;;
+    :) printf "missing argument for -%s\n" "$OPTARG" >&2
+      echo "" >&2
+      usage >&2
+      exit 1
+      ;;
+    \?) printf "ilegal option: -%s\n" "$OPTARG" >&2
+      echo "" >&2
+      usage >&2
+      exit 1
+      ;;
+  esac
 done
 shift $((OPTIND -1))
 [ "${1:-}" = "--" ] && shift
@@ -107,31 +107,31 @@ echo "----------[ Sudo Group Accounts ]---------------"
 grep '^sudo:.*$' /etc/group | cut -d: -f4 | tr ',' ' '
 
 if [[ ${#GROUP_LIST[@]} -ne 0 ]]; then
-    for gr in ${GROUP_LIST[@]}; do
-        echo ""
-        echo "----------[ $gr Group Accounts ]---------------"
-        if grep '^'$gr':.*$' /etc/group > /dev/null 2>&1; then
-            grep '^'$gr':.*$' /etc/group | cut -d: -f4 | tr ',' ' '
-        fi
-    done
+  for gr in ${GROUP_LIST[@]}; do
+    echo ""
+    echo "----------[ $gr Group Accounts ]---------------"
+    if grep '^'$gr':.*$' /etc/group > /dev/null 2>&1; then
+      grep '^'$gr':.*$' /etc/group | cut -d: -f4 | tr ',' ' '
+    fi
+  done
 fi
 
 if [ ${LOCKED_USERS} == true ]; then
-    echo ""
-    echo "---------[ Locked User Accounts ]--------------"
-    shadow="/etc/shadow"
-    if cat $shadow | grep '!' > /dev/null 2>&1; then
-        cat $shadow | grep ! | awk -F ':' '{printf "%s ", $1} END { printf "\n" }'
-    fi
+  echo ""
+  echo "---------[ Locked User Accounts ]--------------"
+  shadow="/etc/shadow"
+  if cat $shadow | grep '!' > /dev/null 2>&1; then
+    cat $shadow | grep ! | awk -F ':' '{printf "%s ", $1} END { printf "\n" }'
+  fi
 
-    echo ""
-    echo "---------[ Expired User Accounts ]-------------"
-    cat $shadow | awk -F ':' -v now=$(date +%s) '{if ( length($8) > 0 && ($8 < (now / 60 / 60 / 24)) ) printf "%s ", $1} END { printf "\n"; }'
+  echo ""
+  echo "---------[ Expired User Accounts ]-------------"
+  cat $shadow | awk -F ':' -v now=$(date +%s) '{if ( length($8) > 0 && ($8 < (now / 60 / 60 / 24)) ) printf "%s ", $1} END { printf "\n"; }'
 fi
 
 if [ ${SYSTEM_USERS} == true ]; then
-    echo ""
-    echo "---------[ System User Accounts ]--------------"
-    awk -F':' -v "min=${l##UID_MIN}" -v "max=${l1##UID_MAX}" '{ if ( !($3 >= min && $3 <= max  && $7 != "/sbin/nologin")) print $0 }' "$_p" | column -s ':' -tn
+  echo ""
+  echo "---------[ System User Accounts ]--------------"
+  awk -F':' -v "min=${l##UID_MIN}" -v "max=${l1##UID_MAX}" '{ if ( !($3 >= min && $3 <= max  && $7 != "/sbin/nologin")) print $0 }' "$_p" | column -s ':' -tn
 fi
 
diff --git a/bin/port-scanner b/bin/port-scanner
--- a/bin/port-scanner
+++ b/bin/port-scanner
@@ -13,7 +13,7 @@ OPTIND=1
 _DELAY=0.005
 
 usage() {
-    LESS=-FEXR less <<HELP
+  LESS=-FEXR less <<HELP
 
 ${BRed}SYNOPSIS${Color_Off}
     ${BRed}$(basename "$0")${Color_Off} [${BRed}-d${Color_Off} ${BGreen}delay${Color_Off}] ${BGreen}hostname or ip address${Color_Off}
@@ -33,23 +33,23 @@ HELP
 }
 
 while getopts 'hd:' option; do
-    case "$option" in
-        h) usage
-            exit
-            ;;
-        d) _DELAY=${OPTARG}
-            ;;
-        :) printf "missing argument for -%s\n" "$OPTARG" >&2
-            echo "" >&2
-            usage >&2
-            exit 1
-            ;;
-        \?) printf "ilegal option: -%s\n" "$OPTARG" >&2
-            echo "" >&2
-            usage >&2
-            exit 1
-            ;;
-    esac
+  case "$option" in
+    h) usage
+      exit
+      ;;
+    d) _DELAY=${OPTARG}
+      ;;
+    :) printf "missing argument for -%s\n" "$OPTARG" >&2
+      echo "" >&2
+      usage >&2
+      exit 1
+      ;;
+    \?) printf "ilegal option: -%s\n" "$OPTARG" >&2
+      echo "" >&2
+      usage >&2
+      exit 1
+      ;;
+  esac
 done
 shift $((OPTIND -1))
 [ "${1:-}" = "--" ] && shift
@@ -60,7 +60,7 @@ ip=${1?You have to specify hostname or ip address}
 printf '\nOpened TCP ports: \n'
 printf '\t'
 for i in {1..65535}; do
-    timeout ${_DELAY} bash -c "echo < /dev/tcp/$ip/$i" &>/dev/null && printf "%d, " "$i"
+  timeout ${_DELAY} bash -c "echo < /dev/tcp/$ip/$i" &>/dev/null && printf "%d, " "$i"
 done
 
 # printf '\nOpened UDP ports: \n'
diff --git a/bin/sshget b/bin/sshget
--- a/bin/sshget
+++ b/bin/sshget
@@ -46,8 +46,8 @@ BIYellow='[1;93m'     # Yellow
 # bash version check
 bash_version=$(printf "%d.%d.%d" ${BASH_VERSINFO[@]:0:3})
 if ! [ $(printf "%s\n%s" "4" "${bash_version}" | sort -V | head -n1) = "4" ]; then
-    echo "This script requires bash version >= 4. Current bash version: ${bash_version}" >&2
-    exit 1
+  echo "This script requires bash version >= 4. Current bash version: ${bash_version}" >&2
+  exit 1
 fi
 
 
@@ -64,15 +64,15 @@ declare -a files=()
 ssh_port=22
 
 err() {
-  printf "${c_red}%s${c_reset}\n" "$*" >&2
+ printf "${c_red}%s${c_reset}\n" "$*" >&2
 }
 
 die() {
-  exit 1
+ exit 1
 }
 
 usage() {
-  LESS=-FEXR less <<HELP
+ LESS=-FEXR less <<HELP
 
 ${BRed}SYNOPSIS${Color_Off}
     ${BRed}$(basename "$0")${Color_Off} [${BRed}-p${Color_Off} ${BGreen}port_number${Color_Off}] ${BGreen}user@host1:/path/to/search${Color_Off}
@@ -91,102 +91,102 @@ HELP
 }
 
 has() {
-  local verbose=0
-  if [[ $1 = '-v' ]]; then
-    verbose=1
-    shift
+ local verbose=0
+ if [[ $1 = '-v' ]]; then
+  verbose=1
+  shift
+ fi
+ for c; do c="${c%% *}"
+  if ! command -v "$c" &> /dev/null; then
+   (( verbose > 0 )) && err "$c not found"
+   return 1
   fi
-  for c; do c="${c%% *}"
-    if ! command -v "$c" &> /dev/null; then
-      (( verbose > 0 )) && err "$c not found"
-      return 1
-    fi
-  done
+ done
 }
 
 has -v fzf rsync || die
 
 cleanup() {
-  [[ -e "$fifo" ]] && rm "$fifo"
+ [[ -e "$fifo" ]] && rm "$fifo"
 }
 
 # argument parsing
 POSITIONAL=()
 while [[ $# -gt 0 ]]; do
-    # make it also '=' separated arguments
-    [[ $1 == --*=* ]] && set -- "${1%%=*}" "${1#*=}" "${@:2}"
-    key="$1"
+  # make it also '=' separated arguments
+  [[ $1 == --*=* ]] && set -- "${1%%=*}" "${1#*=}" "${@:2}"
+  key="$1"
 
-    case $key in
-        -h) usage
-            exit; ;;
-        -p)
-            ssh_port="${2:?$1 needs argument(Usages: $1 argument)}"
-            shift 2 ;;
-        *)
-            POSITIONAL+=("$1")
-            shift ;;
-    esac
+  case $key in
+    -h) usage
+      exit; ;;
+    -p)
+      ssh_port="${2:?$1 needs argument(Usages: $1 argument)}"
+      shift 2 ;;
+    *)
+      POSITIONAL+=("$1")
+      shift ;;
+  esac
 done
 if [ -n "${POSITIONAL:-}" ]; then
-    set -- "${POSITIONAL[@]}"
+  set -- "${POSITIONAL[@]}"
 fi
 ! [[ $ssh_port =~ ^[0-9]+$ && $ssh_port -ge 0 && $ssh_port -le 65535 ]] \
-    && err "$ssh_port is not a valid port" && exit 1
+  && err "$ssh_port is not a valid port" && exit 1
 [[ ${ssh_port} -eq 22 ]] && ssh_cmd="ssh" || ssh_cmd="ssh -p ${ssh_port}"
 
 mkfifo "$fifo"
 
 if (( $# < 1 )); then
-    usage
-    cleanup
-    die
+  usage
+  cleanup
+  die
 fi
 
 for a; do
-    host="${a%:*}"
-    path="${a##*:}"
-    domains+=( ["$a"]="$host" )
-    paths+=( ["$a"]="$path" )
-    shift
+  host="${a%:*}"
+  path="${a##*:}"
+  domains+=( ["$a"]="$host" )
+  paths+=( ["$a"]="$path" )
+  shift
 done
 pswd=
 
 for s in "${!domains[@]}"; do
-    ssh -o PasswordAuthentication=no -o BatchMode=yes "${domains[$s]}" exit &>/dev/null
-    if [[ $? -ne 0 ]]; then
-        if command -v sshpass >/dev/null; then
-            echo -n "Enter the passwd for ${domains[$s]}: "
-            read -s pswd
-            echo
-        else
-            echo "This script requires ssh keypair or sshpass command" >&2
-            echo "Note that sshpass would expose your password in your command line so that it is not recommended in multi-user environment" >&2
-            cleanup
-            exit 1
-        fi
-        SSHPASS=${pswd} sshpass -e ${ssh_cmd} -o StrictHostKeyChecking=no "${domains[$s]}" "find ${paths[$s]}" | sed "s|^|${domains[$s]}:|" >> "$fifo" &
+  ssh -o PasswordAuthentication=no -o BatchMode=yes "${domains[$s]}" exit &>/dev/null
+  if [[ $? -ne 0 ]]; then
+    if command -v sshpass >/dev/null; then
+      echo -n "Enter the passwd for ${domains[$s]}: "
+      read -s pswd
+      echo
     else
-        ${ssh_cmd} -o StrictHostKeyChecking=no "${domains[$s]}" "find ${paths[$s]}" | sed "s|^|${domains[$s]}:|" >> "$fifo" &
+      echo "This script requires ssh keypair or sshpass command" >&2
+      echo "Note that sshpass would expose your password in your command line so that it is not recommended in multi-user environment" >&2
+      cleanup
+      exit 1
     fi
+    SSHPASS=${pswd} sshpass -e ${ssh_cmd} -o StrictHostKeyChecking=no "${domains[$s]}" "find ${paths[$s]}" | sed "s|^|${domains[$s]}:|" >> "$fifo" &
+  else
+    ${ssh_cmd} -o StrictHostKeyChecking=no "${domains[$s]}" "find ${paths[$s]}" | sed "s|^|${domains[$s]}:|" >> "$fifo" &
+  fi
 done
 
 mapfile -t files < <(fzf -e --inline-info --no-sort --multi --bind='Ctrl-A:toggle-all,`:jump' < "$fifo")
 
 if (( ${#files[@]} )); then
-    # https://unix.stackexchange.com/a/222215
-    for idx in ${!files[@]}; do
-        files[idx]="$(echo "${files[idx]// /\\ }" | sed -e "s/:/:\"/" -e "s/$/\"/")"
-        # rsync per file becase of compatability with old version
-        # https://stackoverflow.com/a/15818000
-        if [ -z ${pswd} ]; then
-            rsync -auvzP -e "${ssh_cmd}" "${files[idx]}" .
-        else
-            SSHPASS=${pswd} rsync -auvzP --rsh="$(which sshpass) -e ${ssh_cmd}" ${files[idx]} .
-        fi
-    done
-    # echo rsync -auvzP --dry-run -e "${ssh_cmd}" "${files[@]}" .
-    # echo rsync -auvzP -e "${ssh_cmd}" \'"$(echo "${files[@]// /\\ }" | sed -e "s/:/:\"/" -e "s/$/\"/")"\' .
+  # https://unix.stackexchange.com/a/222215
+  for idx in ${!files[@]}; do
+    files[idx]="$(echo "${files[idx]// /\\ }" | sed -e "s/:/:\"/" -e "s/$/\"/")"
+    # rsync per file becase of compatability with old version
+    # https://stackoverflow.com/a/15818000
+    if [ -z ${pswd} ]; then
+      rsync -auvzP -e "${ssh_cmd}" "${files[idx]}" .
+    else
+      SSHPASS=${pswd} rsync -auvzP --rsh="$(which sshpass) -e ${ssh_cmd}" ${files[idx]} .
+    fi
+  done
+  # echo rsync -auvzP --dry-run -e "${ssh_cmd}" "${files[@]}" .
+  # echo rsync -auvzP -e "${ssh_cmd}" \'"$(echo "${files[@]// /\\ }" | sed -e "s/:/:\"/" -e "s/$/\"/")"\' .
 fi
 
 cleanup
diff --git a/bin/sync-sshconfig b/bin/sync-sshconfig
--- a/bin/sync-sshconfig
+++ b/bin/sync-sshconfig
@@ -24,38 +24,38 @@ HELP
 }
 
 while getopts 'h' option; do
-    case "$option" in
-        h) usage
-            exit
-            ;;
-        :) printf "missing argument for -%s\n" "$OPTARG" >&2
-            echo "" >&2
-            usage >&2
-            exit 1
-            ;;
-        \?) printf "ilegal option: -%s\n" "$OPTARG" >&2
-            echo "" >&2
-            usage >&2
-            exit 1
-            ;;
-    esac
+  case "$option" in
+    h) usage
+      exit
+      ;;
+    :) printf "missing argument for -%s\n" "$OPTARG" >&2
+      echo "" >&2
+      usage >&2
+      exit 1
+      ;;
+    \?) printf "ilegal option: -%s\n" "$OPTARG" >&2
+      echo "" >&2
+      usage >&2
+      exit 1
+      ;;
+  esac
 done
 shift $((OPTIND -1))
 [ "${1:-}" = "--" ] && shift
 
 has() {
-  local verbose=0
-  if [[ $1 = '-v' ]]; then
-    verbose=1
-    shift
+ local verbose=0
+ if [[ $1 = '-v' ]]; then
+  verbose=1
+  shift
+ fi
+ for c; do c="${c%% *}"
+  if ! command -v "$c" &> /dev/null; then
+   (( verbose > 0 )) && err "$c not found"
+   return 1
   fi
-  for c; do c="${c%% *}"
-    if ! command -v "$c" &> /dev/null; then
-      (( verbose > 0 )) && err "$c not found"
-      return 1
-    fi
-  done
-  return 0
+ done
+ return 0
 }
 
 has -v awk fzf || exit 1
@@ -76,96 +76,96 @@ _config=$HOME/.ssh/config
 targets=$(awk '
 BEGIN { current = ""; hosts[0] = ""; hostnames[0] = ""; ips[0] = ""; aliases[0] = "" }
 {
-    if ($1 == "Host") {
-        if ( current != $2 ) {
-            current = $2
-            hosts[current] = $2
-        }
+  if ($1 == "Host") {
+    if ( current != $2 ) {
+      current = $2
+      hosts[current] = $2
     }
-    else if ( $1 == "HostName") {
-        if ( $2 ~ /[a-zA-Z]+/ ) {
-            hostnames[current] = hostnames[current] $2
-        } else if ( $2 ~ /[0-9.]+/ ) {
-            ips[current] = ips[current] "( " $2 " )"
-        }
+  }
+  else if ( $1 == "HostName") {
+    if ( $2 ~ /[a-zA-Z]+/ ) {
+      hostnames[current] = hostnames[current] $2
+    } else if ( $2 ~ /[0-9.]+/ ) {
+      ips[current] = ips[current] "( " $2 " )"
     }
-    else if ( $1 == "#alias" ) {
-        aliases[current] = "["
-        for(i=2;i<=NF;i++) {
-            aliases[current] = aliases[current] " " $i
-        }
-        aliases[current] = aliases[current] " ]"
+  }
+  else if ( $1 == "#alias" ) {
+    aliases[current] = "["
+    for(i=2;i<=NF;i++) {
+      aliases[current] = aliases[current] " " $i
     }
+    aliases[current] = aliases[current] " ]"
+  }
 }
 END {
-    for (key in hosts) {
-        if ( key != 0 ) {
-            print hosts[key], "|->", hostnames[key], "|", ips[key], "|" aliases[key]
-        }
+  for (key in hosts) {
+    if ( key != 0 ) {
+      print hosts[key], "|->", hostnames[key], "|", ips[key], "|" aliases[key]
     }
+  }
 }
 ' $_config | grep -v '*' | column -t -s '|')
 
 exit_code=$?
 [ ${exit_code} != 0 ] && return ${exit_code}
 targets=$(echo "${targets}" \
-    | fzf --bind 'ctrl-a:select-all' --multi \
-    --height=40% --cycle --no-sort --layout=reverse \
-    --preview-window=up:2 \
-    --preview='cat '"$_config"' | grep Host | \
-    awk -v host={} '"'"'{
-        split(host, fld, /->/)
-        gsub(/[ \t]+$/, "", fld[1])
-        if ($0~fld[1]) {
-            getline
-            gsub(/^[ \t]+/,"", $0)
-            print
-            getline
-            if ($0 ~ /HostName/) {
-                gsub(/^[ \t]+/,"", $0)
-                print
-            }
-        }
-    }'"'" | awk '{print $1}')
+  | fzf --bind 'ctrl-a:select-all' --multi \
+  --height=40% --cycle --no-sort --layout=reverse \
+  --preview-window=up:2 \
+  --preview='cat '"$_config"' | grep Host | \
+  awk -v host={} '"'"'{
+    split(host, fld, /->/)
+    gsub(/[ \t]+$/, "", fld[1])
+    if ($0~fld[1]) {
+      getline
+      gsub(/^[ \t]+/,"", $0)
+      print
+      getline
+      if ($0 ~ /HostName/) {
+        gsub(/^[ \t]+/,"", $0)
+        print
+      }
+    }
+  }'"'" | awk '{print $1}')
 
 if [ -z "${targets}" ]; then
-    exit 0
+  exit 0
 fi
 
 use_sshpass=no
 has sshget && \
-    while true; do
-        read -p "Do you want to use sshpass for copying? " yn
-        case $yn in
-            [Yy]* ) use_sshpass=yes; break;;
-            [Nn]* ) :; break;;
-            * ) echo "Please answer yes or no.";;
-        esac
-    done
+  while true; do
+    read -p "Do you want to use sshpass for copying? " yn
+    case $yn in
+      [Yy]* ) use_sshpass=yes; break;;
+      [Nn]* ) :; break;;
+      * ) echo "Please answer yes or no.";;
+    esac
+  done
 
 
 if [ "${use_sshpass}" == yes ]; then
-    echo -n "Enter the passwd for them: "
-    read -s pswd
-    echo
+  echo -n "Enter the passwd for them: "
+  read -s pswd
+  echo
 
-    # https://unix.stackexchange.com/a/107801
-    while IFS= read -u10 -r target; do
-        export SSHPASS=${pswd}
-        (
-        echo "copying to ${target}..."
-        sshpass -e ssh -o ConnectTimeout=2 ${target} mkdir -p ./.ssh
-        sshpass -e scp -o ConnectTimeout=2 ${_config} ${target}:~/.ssh/config
-        [ $? -eq 0 ] && echo "${target} done" || echo "${target} faild" >&2
-        ) &
-    done 10<<< "${targets}"
-    wait
+  # https://unix.stackexchange.com/a/107801
+  while IFS= read -u10 -r target; do
+    export SSHPASS=${pswd}
+    (
+    echo "copying to ${target}..."
+    sshpass -e ssh -o ConnectTimeout=2 ${target} mkdir -p ./.ssh
+    sshpass -e scp -o ConnectTimeout=2 ${_config} ${target}:~/.ssh/config
+    [ $? -eq 0 ] && echo "${target} done" || echo "${target} faild" >&2
+    ) &
+  done 10<<< "${targets}"
+  wait
 else
-    while IFS= read -u10 -r target; do
-        echo "create .ssh directory in ${target}..."
-        ssh -o ConnectTimeout=2 ${target} mkdir -p ./.ssh
-        echo "copying to ${target}..."
-        scp -o ConnectTimeout=2 ${_config} ${target}:~/.ssh/config
-        [ $? -eq 0 ] && echo "${target} done" || echo "${target} faild" >&2
-    done 10<<< "${targets}"
+  while IFS= read -u10 -r target; do
+    echo "create .ssh directory in ${target}..."
+    ssh -o ConnectTimeout=2 ${target} mkdir -p ./.ssh
+    echo "copying to ${target}..."
+    scp -o ConnectTimeout=2 ${_config} ${target}:~/.ssh/config
+    [ $? -eq 0 ] && echo "${target} done" || echo "${target} faild" >&2
+  done 10<<< "${targets}"
 fi
diff --git a/bin/typing-cat b/bin/typing-cat
--- a/bin/typing-cat
+++ b/bin/typing-cat
@@ -13,7 +13,7 @@ OPTIND=1
 t=0.06
 
 usage() {
-    LESS=-FEXR less <<HELP
+  LESS=-FEXR less <<HELP
 
 ${BRed}SYNOPSIS${Color_Off}
     ${BRed}$(basename "$0")${Color_Off} [${BRed}-t${Color_Off} ${BGreen}time_interval${Color_Off}] ${BGreen}file${Color_Off}
@@ -33,31 +33,31 @@ HELP
 }
 
 while getopts 't:h' option; do
-    case "$option" in
-        h) usage
-            exit
-            ;;
-        t) t=${OPTARG}
-            ;;
-        :) printf "missing argument for -%s\n" "$OPTARG" >&2
-            echo "" >&2
-            usage >&2
-            exit 1
-            ;;
-        \?) printf "ilegal option: -%s\n" "$OPTARG" >&2
-            echo "" >&2
-            usage >&2
-            exit 1
-            ;;
-    esac
+  case "$option" in
+    h) usage
+      exit
+      ;;
+    t) t=${OPTARG}
+      ;;
+    :) printf "missing argument for -%s\n" "$OPTARG" >&2
+      echo "" >&2
+      usage >&2
+      exit 1
+      ;;
+    \?) printf "ilegal option: -%s\n" "$OPTARG" >&2
+      echo "" >&2
+      usage >&2
+      exit 1
+      ;;
+  esac
 done
 shift $((OPTIND -1))
 [ "${1:-}" = "--" ] && shift
 
 while IFS= read -r x; do
-    for (( i = 0; i < ${#x}; i++ )); do
-        echo -n "${x[@]:${i}:1}"
-        sleep ${t}
-    done
-    echo
+  for (( i = 0; i < ${#x}; i++ )); do
+    echo -n "${x[@]:${i}:1}"
+    sleep ${t}
+  done
+  echo
 done < "${1:-/dev/stdin}"
